/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './router/__root'
import { Route as routerIndexDotrouteRouteImport } from './router/index.route'
import { Route as routerGuestRouteImport } from './router/_guest'
import { Route as routerProtectedRouteImport } from './router/_protected'
import { Route as featuresAuthMagicLinkDotrouteRouteImport } from './features/auth/magic-link.route'
import { Route as featuresBillingPricingDotrouteRouteImport } from './features/billing/pricing.route'
import { Route as featuresAuthResetPasswordDotrouteRouteImport } from './features/auth/reset-password.route'
import { Route as featuresAuthTwoFactorDotrouteRouteImport } from './features/auth/two-factor.route'
import { Route as featuresAuthVerifyEmailDotrouteRouteImport } from './features/auth/verify-email.route'
import { Route as featuresAuthForgotPasswordDotrouteRouteImport } from './features/auth/forgot-password.route'
import { Route as featuresAuthSignInDotrouteRouteImport } from './features/auth/sign-in.route'
import { Route as featuresAuthSignUpDotrouteRouteImport } from './features/auth/sign-up.route'
import { Route as routerShellRouteImport } from './router/_shell'
import { Route as featuresInvitationsAcceptDotrouteRouteImport } from './features/invitations/accept.route'
import { Route as featuresDevelopersEventsDotrouteRouteImport } from './features/developers/events.route'
import { Route as featuresLegalAccessibilityDotrouteRouteImport } from './features/legal/accessibility.route'
import { Route as featuresLegalCookiesDotrouteRouteImport } from './features/legal/cookies.route'
import { Route as featuresLegalDataRightsDotrouteRouteImport } from './features/legal/data-rights.route'
import { Route as featuresLegalPrivacyPolicyDotrouteRouteImport } from './features/legal/privacy-policy.route'
import { Route as featuresLegalSubProcessorsDotrouteRouteImport } from './features/legal/sub-processors.route'
import { Route as featuresLegalTermsDotrouteRouteImport } from './features/legal/terms.route'
import { Route as routerAdminRouteImport } from './router/_admin'
import { Route as featuresDashboardDashboardDotrouteRouteImport } from './features/dashboard/dashboard.route'
import { Route as routerSettingsRouteImport } from './router/settings'
import { Route as featuresLegalAcceptDotrouteRouteImport } from './features/legal/accept.route'
import { Route as featuresOrganizationNewDotrouteRouteImport } from './features/organization/new.route'
import { Route as routerSettingsIndexDotrouteRouteImport } from './router/settings-index.route'
import { Route as routerOrgScopeRouteImport } from './router/_org-scope'
import { Route as featuresAccountAccountDotrouteRouteImport } from './features/account/account.route'
import { Route as featuresApiTokensApiTokensDotrouteRouteImport } from './features/api-tokens/api-tokens.route'
import { Route as featuresNotificationsNotificationsDotrouteRouteImport } from './features/notifications/notifications.route'
import { Route as featuresPrivacyPrivacyDotrouteRouteImport } from './features/privacy/privacy.route'
import { Route as featuresAdminAuditLogAdminAuditLogDotrouteRouteImport } from './features/admin-audit-log/admin-audit-log.route'
import { Route as featuresAdminOrgsAdminOrgsDotrouteRouteImport } from './features/admin-orgs/admin-orgs.route'
import { Route as featuresAdminUsersAdminUsersDotrouteRouteImport } from './features/admin-users/admin-users.route'
import { Route as featuresBillingBillingDotrouteRouteImport } from './features/billing/billing.route'
import { Route as featuresOrganizationOrganizationDotrouteRouteImport } from './features/organization/organization.route'
import { Route as featuresSsoSsoDotrouteRouteImport } from './features/sso/sso.route'
import { Route as featuresWebhooksWebhooksDotrouteRouteImport } from './features/webhooks/webhooks.route'
import { Route as featuresAdminOrgsAdminOrgDetailDotrouteRouteImport } from './features/admin-orgs/admin-org-detail.route'
import { Route as featuresAdminUsersAdminUserDetailDotrouteRouteImport } from './features/admin-users/admin-user-detail.route'

const routerIndexDotrouteRoute = routerIndexDotrouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const routerGuestRoute = routerGuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const routerProtectedRoute = routerProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresAuthMagicLinkDotrouteRoute =
  featuresAuthMagicLinkDotrouteRouteImport.update({
    id: '/magic-link',
    path: '/magic-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresBillingPricingDotrouteRoute =
  featuresBillingPricingDotrouteRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresAuthResetPasswordDotrouteRoute =
  featuresAuthResetPasswordDotrouteRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresAuthTwoFactorDotrouteRoute =
  featuresAuthTwoFactorDotrouteRouteImport.update({
    id: '/two-factor',
    path: '/two-factor',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresAuthVerifyEmailDotrouteRoute =
  featuresAuthVerifyEmailDotrouteRouteImport.update({
    id: '/verify-email',
    path: '/verify-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresAuthForgotPasswordDotrouteRoute =
  featuresAuthForgotPasswordDotrouteRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => routerGuestRoute,
  } as any)
const featuresAuthSignInDotrouteRoute =
  featuresAuthSignInDotrouteRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => routerGuestRoute,
  } as any)
const featuresAuthSignUpDotrouteRoute =
  featuresAuthSignUpDotrouteRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => routerGuestRoute,
  } as any)
const routerShellRoute = routerShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => routerProtectedRoute,
} as any)
const featuresInvitationsAcceptDotrouteRoute =
  featuresInvitationsAcceptDotrouteRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresDevelopersEventsDotrouteRoute =
  featuresDevelopersEventsDotrouteRouteImport.update({
    id: '/developers/events',
    path: '/developers/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresLegalAccessibilityDotrouteRoute =
  featuresLegalAccessibilityDotrouteRouteImport.update({
    id: '/legal/accessibility',
    path: '/legal/accessibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresLegalCookiesDotrouteRoute =
  featuresLegalCookiesDotrouteRouteImport.update({
    id: '/legal/cookies',
    path: '/legal/cookies',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresLegalDataRightsDotrouteRoute =
  featuresLegalDataRightsDotrouteRouteImport.update({
    id: '/legal/data-rights',
    path: '/legal/data-rights',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresLegalPrivacyPolicyDotrouteRoute =
  featuresLegalPrivacyPolicyDotrouteRouteImport.update({
    id: '/legal/privacy-policy',
    path: '/legal/privacy-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresLegalSubProcessorsDotrouteRoute =
  featuresLegalSubProcessorsDotrouteRouteImport.update({
    id: '/legal/sub-processors',
    path: '/legal/sub-processors',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresLegalTermsDotrouteRoute =
  featuresLegalTermsDotrouteRouteImport.update({
    id: '/legal/terms',
    path: '/legal/terms',
    getParentRoute: () => rootRouteImport,
  } as any)
const routerAdminRoute = routerAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => routerShellRoute,
} as any)
const featuresDashboardDashboardDotrouteRoute =
  featuresDashboardDashboardDotrouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => routerShellRoute,
  } as any)
const routerSettingsRoute = routerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => routerShellRoute,
} as any)
const featuresLegalAcceptDotrouteRoute =
  featuresLegalAcceptDotrouteRouteImport.update({
    id: '/legal/accept',
    path: '/legal/accept',
    getParentRoute: () => routerProtectedRoute,
  } as any)
const featuresOrganizationNewDotrouteRoute =
  featuresOrganizationNewDotrouteRouteImport.update({
    id: '/org/new',
    path: '/org/new',
    getParentRoute: () => routerShellRoute,
  } as any)
const routerSettingsIndexDotrouteRoute =
  routerSettingsIndexDotrouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => routerSettingsRoute,
  } as any)
const routerOrgScopeRoute = routerOrgScopeRouteImport.update({
  id: '/_org-scope',
  getParentRoute: () => routerSettingsRoute,
} as any)
const featuresAccountAccountDotrouteRoute =
  featuresAccountAccountDotrouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => routerSettingsRoute,
  } as any)
const featuresApiTokensApiTokensDotrouteRoute =
  featuresApiTokensApiTokensDotrouteRouteImport.update({
    id: '/api-tokens',
    path: '/api-tokens',
    getParentRoute: () => routerSettingsRoute,
  } as any)
const featuresNotificationsNotificationsDotrouteRoute =
  featuresNotificationsNotificationsDotrouteRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => routerSettingsRoute,
  } as any)
const featuresPrivacyPrivacyDotrouteRoute =
  featuresPrivacyPrivacyDotrouteRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => routerSettingsRoute,
  } as any)
const featuresAdminAuditLogAdminAuditLogDotrouteRoute =
  featuresAdminAuditLogAdminAuditLogDotrouteRouteImport.update({
    id: '/admin/audit-log',
    path: '/admin/audit-log',
    getParentRoute: () => routerAdminRoute,
  } as any)
const featuresAdminOrgsAdminOrgsDotrouteRoute =
  featuresAdminOrgsAdminOrgsDotrouteRouteImport.update({
    id: '/admin/orgs',
    path: '/admin/orgs',
    getParentRoute: () => routerAdminRoute,
  } as any)
const featuresAdminUsersAdminUsersDotrouteRoute =
  featuresAdminUsersAdminUsersDotrouteRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => routerAdminRoute,
  } as any)
const featuresBillingBillingDotrouteRoute =
  featuresBillingBillingDotrouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => routerOrgScopeRoute,
  } as any)
const featuresOrganizationOrganizationDotrouteRoute =
  featuresOrganizationOrganizationDotrouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => routerOrgScopeRoute,
  } as any)
const featuresSsoSsoDotrouteRoute = featuresSsoSsoDotrouteRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => routerOrgScopeRoute,
} as any)
const featuresWebhooksWebhooksDotrouteRoute =
  featuresWebhooksWebhooksDotrouteRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => routerOrgScopeRoute,
  } as any)
const featuresAdminOrgsAdminOrgDetailDotrouteRoute =
  featuresAdminOrgsAdminOrgDetailDotrouteRouteImport.update({
    id: '/admin/orgs/$orgId',
    path: '/admin/orgs/$orgId',
    getParentRoute: () => routerAdminRoute,
  } as any)
const featuresAdminUsersAdminUserDetailDotrouteRoute =
  featuresAdminUsersAdminUserDetailDotrouteRouteImport.update({
    id: '/admin/users/$id',
    path: '/admin/users/$id',
    getParentRoute: () => routerAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof routerIndexDotrouteRoute
  '/magic-link': typeof featuresAuthMagicLinkDotrouteRoute
  '/pricing': typeof featuresBillingPricingDotrouteRoute
  '/reset-password': typeof featuresAuthResetPasswordDotrouteRoute
  '/two-factor': typeof featuresAuthTwoFactorDotrouteRoute
  '/verify-email': typeof featuresAuthVerifyEmailDotrouteRoute
  '/forgot-password': typeof featuresAuthForgotPasswordDotrouteRoute
  '/sign-in': typeof featuresAuthSignInDotrouteRoute
  '/sign-up': typeof featuresAuthSignUpDotrouteRoute
  '/accept-invitation/$invitationId': typeof featuresInvitationsAcceptDotrouteRoute
  '/developers/events': typeof featuresDevelopersEventsDotrouteRoute
  '/legal/accessibility': typeof featuresLegalAccessibilityDotrouteRoute
  '/legal/cookies': typeof featuresLegalCookiesDotrouteRoute
  '/legal/data-rights': typeof featuresLegalDataRightsDotrouteRoute
  '/legal/privacy-policy': typeof featuresLegalPrivacyPolicyDotrouteRoute
  '/legal/sub-processors': typeof featuresLegalSubProcessorsDotrouteRoute
  '/legal/terms': typeof featuresLegalTermsDotrouteRoute
  '/dashboard': typeof featuresDashboardDashboardDotrouteRoute
  '/legal/accept': typeof featuresLegalAcceptDotrouteRoute
  '/settings': typeof routerSettingsRouteWithChildren
  '/settings/': typeof routerSettingsIndexDotrouteRoute
  '/org/new': typeof featuresOrganizationNewDotrouteRoute
  '/settings/account': typeof featuresAccountAccountDotrouteRoute
  '/settings/api-tokens': typeof featuresApiTokensApiTokensDotrouteRoute
  '/settings/notifications': typeof featuresNotificationsNotificationsDotrouteRoute
  '/settings/privacy': typeof featuresPrivacyPrivacyDotrouteRoute
  '/admin/audit-log': typeof featuresAdminAuditLogAdminAuditLogDotrouteRoute
  '/admin/orgs': typeof featuresAdminOrgsAdminOrgsDotrouteRoute
  '/admin/users': typeof featuresAdminUsersAdminUsersDotrouteRoute
  '/settings/billing': typeof featuresBillingBillingDotrouteRoute
  '/settings/organization': typeof featuresOrganizationOrganizationDotrouteRoute
  '/settings/sso': typeof featuresSsoSsoDotrouteRoute
  '/settings/webhooks': typeof featuresWebhooksWebhooksDotrouteRoute
  '/admin/orgs/$orgId': typeof featuresAdminOrgsAdminOrgDetailDotrouteRoute
  '/admin/users/$id': typeof featuresAdminUsersAdminUserDetailDotrouteRoute
}
export interface FileRoutesByTo {
  '/': typeof routerIndexDotrouteRoute
  '/magic-link': typeof featuresAuthMagicLinkDotrouteRoute
  '/pricing': typeof featuresBillingPricingDotrouteRoute
  '/reset-password': typeof featuresAuthResetPasswordDotrouteRoute
  '/two-factor': typeof featuresAuthTwoFactorDotrouteRoute
  '/verify-email': typeof featuresAuthVerifyEmailDotrouteRoute
  '/forgot-password': typeof featuresAuthForgotPasswordDotrouteRoute
  '/sign-in': typeof featuresAuthSignInDotrouteRoute
  '/sign-up': typeof featuresAuthSignUpDotrouteRoute
  '/accept-invitation/$invitationId': typeof featuresInvitationsAcceptDotrouteRoute
  '/developers/events': typeof featuresDevelopersEventsDotrouteRoute
  '/legal/accessibility': typeof featuresLegalAccessibilityDotrouteRoute
  '/legal/cookies': typeof featuresLegalCookiesDotrouteRoute
  '/legal/data-rights': typeof featuresLegalDataRightsDotrouteRoute
  '/legal/privacy-policy': typeof featuresLegalPrivacyPolicyDotrouteRoute
  '/legal/sub-processors': typeof featuresLegalSubProcessorsDotrouteRoute
  '/legal/terms': typeof featuresLegalTermsDotrouteRoute
  '/dashboard': typeof featuresDashboardDashboardDotrouteRoute
  '/legal/accept': typeof featuresLegalAcceptDotrouteRoute
  '/settings': typeof routerSettingsIndexDotrouteRoute
  '/org/new': typeof featuresOrganizationNewDotrouteRoute
  '/settings/account': typeof featuresAccountAccountDotrouteRoute
  '/settings/api-tokens': typeof featuresApiTokensApiTokensDotrouteRoute
  '/settings/notifications': typeof featuresNotificationsNotificationsDotrouteRoute
  '/settings/privacy': typeof featuresPrivacyPrivacyDotrouteRoute
  '/admin/audit-log': typeof featuresAdminAuditLogAdminAuditLogDotrouteRoute
  '/admin/orgs': typeof featuresAdminOrgsAdminOrgsDotrouteRoute
  '/admin/users': typeof featuresAdminUsersAdminUsersDotrouteRoute
  '/settings/billing': typeof featuresBillingBillingDotrouteRoute
  '/settings/organization': typeof featuresOrganizationOrganizationDotrouteRoute
  '/settings/sso': typeof featuresSsoSsoDotrouteRoute
  '/settings/webhooks': typeof featuresWebhooksWebhooksDotrouteRoute
  '/admin/orgs/$orgId': typeof featuresAdminOrgsAdminOrgDetailDotrouteRoute
  '/admin/users/$id': typeof featuresAdminUsersAdminUserDetailDotrouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof routerIndexDotrouteRoute
  '/magic-link': typeof featuresAuthMagicLinkDotrouteRoute
  '/pricing': typeof featuresBillingPricingDotrouteRoute
  '/reset-password': typeof featuresAuthResetPasswordDotrouteRoute
  '/two-factor': typeof featuresAuthTwoFactorDotrouteRoute
  '/verify-email': typeof featuresAuthVerifyEmailDotrouteRoute
  '/_guest': typeof routerGuestRouteWithChildren
  '/_protected': typeof routerProtectedRouteWithChildren
  '/_guest/forgot-password': typeof featuresAuthForgotPasswordDotrouteRoute
  '/_guest/sign-in': typeof featuresAuthSignInDotrouteRoute
  '/_guest/sign-up': typeof featuresAuthSignUpDotrouteRoute
  '/accept-invitation/$invitationId': typeof featuresInvitationsAcceptDotrouteRoute
  '/developers/events': typeof featuresDevelopersEventsDotrouteRoute
  '/legal/accessibility': typeof featuresLegalAccessibilityDotrouteRoute
  '/legal/cookies': typeof featuresLegalCookiesDotrouteRoute
  '/legal/data-rights': typeof featuresLegalDataRightsDotrouteRoute
  '/legal/privacy-policy': typeof featuresLegalPrivacyPolicyDotrouteRoute
  '/legal/sub-processors': typeof featuresLegalSubProcessorsDotrouteRoute
  '/legal/terms': typeof featuresLegalTermsDotrouteRoute
  '/_protected/_shell': typeof routerShellRouteWithChildren
  '/_protected/_shell/dashboard': typeof featuresDashboardDashboardDotrouteRoute
  '/_protected/legal/accept': typeof featuresLegalAcceptDotrouteRoute
  '/_protected/_shell/_admin': typeof routerAdminRouteWithChildren
  '/_protected/_shell/settings': typeof routerSettingsRouteWithChildren
  '/_protected/_shell/settings/': typeof routerSettingsIndexDotrouteRoute
  '/_protected/_shell/org/new': typeof featuresOrganizationNewDotrouteRoute
  '/_protected/_shell/settings/account': typeof featuresAccountAccountDotrouteRoute
  '/_protected/_shell/settings/api-tokens': typeof featuresApiTokensApiTokensDotrouteRoute
  '/_protected/_shell/settings/notifications': typeof featuresNotificationsNotificationsDotrouteRoute
  '/_protected/_shell/settings/privacy': typeof featuresPrivacyPrivacyDotrouteRoute
  '/_protected/_shell/settings/_org-scope': typeof routerOrgScopeRouteWithChildren
  '/_protected/_shell/_admin/admin/audit-log': typeof featuresAdminAuditLogAdminAuditLogDotrouteRoute
  '/_protected/_shell/_admin/admin/orgs': typeof featuresAdminOrgsAdminOrgsDotrouteRoute
  '/_protected/_shell/_admin/admin/users': typeof featuresAdminUsersAdminUsersDotrouteRoute
  '/_protected/_shell/settings/_org-scope/billing': typeof featuresBillingBillingDotrouteRoute
  '/_protected/_shell/settings/_org-scope/organization': typeof featuresOrganizationOrganizationDotrouteRoute
  '/_protected/_shell/settings/_org-scope/sso': typeof featuresSsoSsoDotrouteRoute
  '/_protected/_shell/settings/_org-scope/webhooks': typeof featuresWebhooksWebhooksDotrouteRoute
  '/_protected/_shell/_admin/admin/orgs/$orgId': typeof featuresAdminOrgsAdminOrgDetailDotrouteRoute
  '/_protected/_shell/_admin/admin/users/$id': typeof featuresAdminUsersAdminUserDetailDotrouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/magic-link'
    | '/pricing'
    | '/reset-password'
    | '/two-factor'
    | '/verify-email'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/accept-invitation/$invitationId'
    | '/developers/events'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/data-rights'
    | '/legal/privacy-policy'
    | '/legal/sub-processors'
    | '/legal/terms'
    | '/dashboard'
    | '/legal/accept'
    | '/settings'
    | '/settings/'
    | '/org/new'
    | '/settings/account'
    | '/settings/api-tokens'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/admin/audit-log'
    | '/admin/orgs'
    | '/admin/users'
    | '/settings/billing'
    | '/settings/organization'
    | '/settings/sso'
    | '/settings/webhooks'
    | '/admin/orgs/$orgId'
    | '/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/magic-link'
    | '/pricing'
    | '/reset-password'
    | '/two-factor'
    | '/verify-email'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/accept-invitation/$invitationId'
    | '/developers/events'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/data-rights'
    | '/legal/privacy-policy'
    | '/legal/sub-processors'
    | '/legal/terms'
    | '/dashboard'
    | '/legal/accept'
    | '/settings'
    | '/org/new'
    | '/settings/account'
    | '/settings/api-tokens'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/admin/audit-log'
    | '/admin/orgs'
    | '/admin/users'
    | '/settings/billing'
    | '/settings/organization'
    | '/settings/sso'
    | '/settings/webhooks'
    | '/admin/orgs/$orgId'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/magic-link'
    | '/pricing'
    | '/reset-password'
    | '/two-factor'
    | '/verify-email'
    | '/_guest'
    | '/_protected'
    | '/_guest/forgot-password'
    | '/_guest/sign-in'
    | '/_guest/sign-up'
    | '/accept-invitation/$invitationId'
    | '/developers/events'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/data-rights'
    | '/legal/privacy-policy'
    | '/legal/sub-processors'
    | '/legal/terms'
    | '/_protected/_shell'
    | '/_protected/_shell/dashboard'
    | '/_protected/legal/accept'
    | '/_protected/_shell/_admin'
    | '/_protected/_shell/settings'
    | '/_protected/_shell/settings/'
    | '/_protected/_shell/org/new'
    | '/_protected/_shell/settings/account'
    | '/_protected/_shell/settings/api-tokens'
    | '/_protected/_shell/settings/notifications'
    | '/_protected/_shell/settings/privacy'
    | '/_protected/_shell/settings/_org-scope'
    | '/_protected/_shell/_admin/admin/audit-log'
    | '/_protected/_shell/_admin/admin/orgs'
    | '/_protected/_shell/_admin/admin/users'
    | '/_protected/_shell/settings/_org-scope/billing'
    | '/_protected/_shell/settings/_org-scope/organization'
    | '/_protected/_shell/settings/_org-scope/sso'
    | '/_protected/_shell/settings/_org-scope/webhooks'
    | '/_protected/_shell/_admin/admin/orgs/$orgId'
    | '/_protected/_shell/_admin/admin/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  routerIndexDotrouteRoute: typeof routerIndexDotrouteRoute
  featuresAuthMagicLinkDotrouteRoute: typeof featuresAuthMagicLinkDotrouteRoute
  featuresBillingPricingDotrouteRoute: typeof featuresBillingPricingDotrouteRoute
  featuresAuthResetPasswordDotrouteRoute: typeof featuresAuthResetPasswordDotrouteRoute
  featuresAuthTwoFactorDotrouteRoute: typeof featuresAuthTwoFactorDotrouteRoute
  featuresAuthVerifyEmailDotrouteRoute: typeof featuresAuthVerifyEmailDotrouteRoute
  routerGuestRoute: typeof routerGuestRouteWithChildren
  routerProtectedRoute: typeof routerProtectedRouteWithChildren
  featuresInvitationsAcceptDotrouteRoute: typeof featuresInvitationsAcceptDotrouteRoute
  featuresDevelopersEventsDotrouteRoute: typeof featuresDevelopersEventsDotrouteRoute
  featuresLegalAccessibilityDotrouteRoute: typeof featuresLegalAccessibilityDotrouteRoute
  featuresLegalCookiesDotrouteRoute: typeof featuresLegalCookiesDotrouteRoute
  featuresLegalDataRightsDotrouteRoute: typeof featuresLegalDataRightsDotrouteRoute
  featuresLegalPrivacyPolicyDotrouteRoute: typeof featuresLegalPrivacyPolicyDotrouteRoute
  featuresLegalSubProcessorsDotrouteRoute: typeof featuresLegalSubProcessorsDotrouteRoute
  featuresLegalTermsDotrouteRoute: typeof featuresLegalTermsDotrouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof routerIndexDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof routerGuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof routerProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof featuresAuthMagicLinkDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof featuresBillingPricingDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof featuresAuthResetPasswordDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof featuresAuthTwoFactorDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof featuresAuthVerifyEmailDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof featuresAuthForgotPasswordDotrouteRouteImport
      parentRoute: typeof routerGuestRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof featuresAuthSignInDotrouteRouteImport
      parentRoute: typeof routerGuestRoute
    }
    '/_guest/sign-up': {
      id: '/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof featuresAuthSignUpDotrouteRouteImport
      parentRoute: typeof routerGuestRoute
    }
    '/_protected/_shell': {
      id: '/_protected/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof routerShellRouteImport
      parentRoute: typeof routerProtectedRoute
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof featuresInvitationsAcceptDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/events': {
      id: '/developers/events'
      path: '/developers/events'
      fullPath: '/developers/events'
      preLoaderRoute: typeof featuresDevelopersEventsDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/accessibility': {
      id: '/legal/accessibility'
      path: '/legal/accessibility'
      fullPath: '/legal/accessibility'
      preLoaderRoute: typeof featuresLegalAccessibilityDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof featuresLegalCookiesDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/data-rights': {
      id: '/legal/data-rights'
      path: '/legal/data-rights'
      fullPath: '/legal/data-rights'
      preLoaderRoute: typeof featuresLegalDataRightsDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof featuresLegalPrivacyPolicyDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/sub-processors': {
      id: '/legal/sub-processors'
      path: '/legal/sub-processors'
      fullPath: '/legal/sub-processors'
      preLoaderRoute: typeof featuresLegalSubProcessorsDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof featuresLegalTermsDotrouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_shell/_admin': {
      id: '/_protected/_shell/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof routerAdminRouteImport
      parentRoute: typeof routerShellRoute
    }
    '/_protected/_shell/dashboard': {
      id: '/_protected/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof featuresDashboardDashboardDotrouteRouteImport
      parentRoute: typeof routerShellRoute
    }
    '/_protected/_shell/settings': {
      id: '/_protected/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof routerSettingsRouteImport
      parentRoute: typeof routerShellRoute
    }
    '/_protected/legal/accept': {
      id: '/_protected/legal/accept'
      path: '/legal/accept'
      fullPath: '/legal/accept'
      preLoaderRoute: typeof featuresLegalAcceptDotrouteRouteImport
      parentRoute: typeof routerProtectedRoute
    }
    '/_protected/_shell/org/new': {
      id: '/_protected/_shell/org/new'
      path: '/org/new'
      fullPath: '/org/new'
      preLoaderRoute: typeof featuresOrganizationNewDotrouteRouteImport
      parentRoute: typeof routerShellRoute
    }
    '/_protected/_shell/settings/': {
      id: '/_protected/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof routerSettingsIndexDotrouteRouteImport
      parentRoute: typeof routerSettingsRoute
    }
    '/_protected/_shell/settings/_org-scope': {
      id: '/_protected/_shell/settings/_org-scope'
      path: ''
      fullPath: '/settings'
      preLoaderRoute: typeof routerOrgScopeRouteImport
      parentRoute: typeof routerSettingsRoute
    }
    '/_protected/_shell/settings/account': {
      id: '/_protected/_shell/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof featuresAccountAccountDotrouteRouteImport
      parentRoute: typeof routerSettingsRoute
    }
    '/_protected/_shell/settings/api-tokens': {
      id: '/_protected/_shell/settings/api-tokens'
      path: '/api-tokens'
      fullPath: '/settings/api-tokens'
      preLoaderRoute: typeof featuresApiTokensApiTokensDotrouteRouteImport
      parentRoute: typeof routerSettingsRoute
    }
    '/_protected/_shell/settings/notifications': {
      id: '/_protected/_shell/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof featuresNotificationsNotificationsDotrouteRouteImport
      parentRoute: typeof routerSettingsRoute
    }
    '/_protected/_shell/settings/privacy': {
      id: '/_protected/_shell/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof featuresPrivacyPrivacyDotrouteRouteImport
      parentRoute: typeof routerSettingsRoute
    }
    '/_protected/_shell/_admin/admin/audit-log': {
      id: '/_protected/_shell/_admin/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof featuresAdminAuditLogAdminAuditLogDotrouteRouteImport
      parentRoute: typeof routerAdminRoute
    }
    '/_protected/_shell/_admin/admin/orgs': {
      id: '/_protected/_shell/_admin/admin/orgs'
      path: '/admin/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof featuresAdminOrgsAdminOrgsDotrouteRouteImport
      parentRoute: typeof routerAdminRoute
    }
    '/_protected/_shell/_admin/admin/users': {
      id: '/_protected/_shell/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof featuresAdminUsersAdminUsersDotrouteRouteImport
      parentRoute: typeof routerAdminRoute
    }
    '/_protected/_shell/settings/_org-scope/billing': {
      id: '/_protected/_shell/settings/_org-scope/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof featuresBillingBillingDotrouteRouteImport
      parentRoute: typeof routerOrgScopeRoute
    }
    '/_protected/_shell/settings/_org-scope/organization': {
      id: '/_protected/_shell/settings/_org-scope/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof featuresOrganizationOrganizationDotrouteRouteImport
      parentRoute: typeof routerOrgScopeRoute
    }
    '/_protected/_shell/settings/_org-scope/sso': {
      id: '/_protected/_shell/settings/_org-scope/sso'
      path: '/sso'
      fullPath: '/settings/sso'
      preLoaderRoute: typeof featuresSsoSsoDotrouteRouteImport
      parentRoute: typeof routerOrgScopeRoute
    }
    '/_protected/_shell/settings/_org-scope/webhooks': {
      id: '/_protected/_shell/settings/_org-scope/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof featuresWebhooksWebhooksDotrouteRouteImport
      parentRoute: typeof routerOrgScopeRoute
    }
    '/_protected/_shell/_admin/admin/orgs/$orgId': {
      id: '/_protected/_shell/_admin/admin/orgs/$orgId'
      path: '/admin/orgs/$orgId'
      fullPath: '/admin/orgs/$orgId'
      preLoaderRoute: typeof featuresAdminOrgsAdminOrgDetailDotrouteRouteImport
      parentRoute: typeof routerAdminRoute
    }
    '/_protected/_shell/_admin/admin/users/$id': {
      id: '/_protected/_shell/_admin/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof featuresAdminUsersAdminUserDetailDotrouteRouteImport
      parentRoute: typeof routerAdminRoute
    }
  }
}

interface routerGuestRouteChildren {
  featuresAuthForgotPasswordDotrouteRoute: typeof featuresAuthForgotPasswordDotrouteRoute
  featuresAuthSignInDotrouteRoute: typeof featuresAuthSignInDotrouteRoute
  featuresAuthSignUpDotrouteRoute: typeof featuresAuthSignUpDotrouteRoute
}

const routerGuestRouteChildren: routerGuestRouteChildren = {
  featuresAuthForgotPasswordDotrouteRoute:
    featuresAuthForgotPasswordDotrouteRoute,
  featuresAuthSignInDotrouteRoute: featuresAuthSignInDotrouteRoute,
  featuresAuthSignUpDotrouteRoute: featuresAuthSignUpDotrouteRoute,
}

const routerGuestRouteWithChildren = routerGuestRoute._addFileChildren(
  routerGuestRouteChildren,
)

interface routerAdminRouteChildren {
  featuresAdminAuditLogAdminAuditLogDotrouteRoute: typeof featuresAdminAuditLogAdminAuditLogDotrouteRoute
  featuresAdminOrgsAdminOrgsDotrouteRoute: typeof featuresAdminOrgsAdminOrgsDotrouteRoute
  featuresAdminUsersAdminUsersDotrouteRoute: typeof featuresAdminUsersAdminUsersDotrouteRoute
  featuresAdminOrgsAdminOrgDetailDotrouteRoute: typeof featuresAdminOrgsAdminOrgDetailDotrouteRoute
  featuresAdminUsersAdminUserDetailDotrouteRoute: typeof featuresAdminUsersAdminUserDetailDotrouteRoute
}

const routerAdminRouteChildren: routerAdminRouteChildren = {
  featuresAdminAuditLogAdminAuditLogDotrouteRoute:
    featuresAdminAuditLogAdminAuditLogDotrouteRoute,
  featuresAdminOrgsAdminOrgsDotrouteRoute:
    featuresAdminOrgsAdminOrgsDotrouteRoute,
  featuresAdminUsersAdminUsersDotrouteRoute:
    featuresAdminUsersAdminUsersDotrouteRoute,
  featuresAdminOrgsAdminOrgDetailDotrouteRoute:
    featuresAdminOrgsAdminOrgDetailDotrouteRoute,
  featuresAdminUsersAdminUserDetailDotrouteRoute:
    featuresAdminUsersAdminUserDetailDotrouteRoute,
}

const routerAdminRouteWithChildren = routerAdminRoute._addFileChildren(
  routerAdminRouteChildren,
)

interface routerOrgScopeRouteChildren {
  featuresBillingBillingDotrouteRoute: typeof featuresBillingBillingDotrouteRoute
  featuresOrganizationOrganizationDotrouteRoute: typeof featuresOrganizationOrganizationDotrouteRoute
  featuresSsoSsoDotrouteRoute: typeof featuresSsoSsoDotrouteRoute
  featuresWebhooksWebhooksDotrouteRoute: typeof featuresWebhooksWebhooksDotrouteRoute
}

const routerOrgScopeRouteChildren: routerOrgScopeRouteChildren = {
  featuresBillingBillingDotrouteRoute: featuresBillingBillingDotrouteRoute,
  featuresOrganizationOrganizationDotrouteRoute:
    featuresOrganizationOrganizationDotrouteRoute,
  featuresSsoSsoDotrouteRoute: featuresSsoSsoDotrouteRoute,
  featuresWebhooksWebhooksDotrouteRoute: featuresWebhooksWebhooksDotrouteRoute,
}

const routerOrgScopeRouteWithChildren = routerOrgScopeRoute._addFileChildren(
  routerOrgScopeRouteChildren,
)

interface routerSettingsRouteChildren {
  routerSettingsIndexDotrouteRoute: typeof routerSettingsIndexDotrouteRoute
  featuresAccountAccountDotrouteRoute: typeof featuresAccountAccountDotrouteRoute
  featuresApiTokensApiTokensDotrouteRoute: typeof featuresApiTokensApiTokensDotrouteRoute
  featuresNotificationsNotificationsDotrouteRoute: typeof featuresNotificationsNotificationsDotrouteRoute
  featuresPrivacyPrivacyDotrouteRoute: typeof featuresPrivacyPrivacyDotrouteRoute
  routerOrgScopeRoute: typeof routerOrgScopeRouteWithChildren
}

const routerSettingsRouteChildren: routerSettingsRouteChildren = {
  routerSettingsIndexDotrouteRoute: routerSettingsIndexDotrouteRoute,
  featuresAccountAccountDotrouteRoute: featuresAccountAccountDotrouteRoute,
  featuresApiTokensApiTokensDotrouteRoute:
    featuresApiTokensApiTokensDotrouteRoute,
  featuresNotificationsNotificationsDotrouteRoute:
    featuresNotificationsNotificationsDotrouteRoute,
  featuresPrivacyPrivacyDotrouteRoute: featuresPrivacyPrivacyDotrouteRoute,
  routerOrgScopeRoute: routerOrgScopeRouteWithChildren,
}

const routerSettingsRouteWithChildren = routerSettingsRoute._addFileChildren(
  routerSettingsRouteChildren,
)

interface routerShellRouteChildren {
  featuresDashboardDashboardDotrouteRoute: typeof featuresDashboardDashboardDotrouteRoute
  routerAdminRoute: typeof routerAdminRouteWithChildren
  routerSettingsRoute: typeof routerSettingsRouteWithChildren
  featuresOrganizationNewDotrouteRoute: typeof featuresOrganizationNewDotrouteRoute
}

const routerShellRouteChildren: routerShellRouteChildren = {
  featuresDashboardDashboardDotrouteRoute:
    featuresDashboardDashboardDotrouteRoute,
  routerAdminRoute: routerAdminRouteWithChildren,
  routerSettingsRoute: routerSettingsRouteWithChildren,
  featuresOrganizationNewDotrouteRoute: featuresOrganizationNewDotrouteRoute,
}

const routerShellRouteWithChildren = routerShellRoute._addFileChildren(
  routerShellRouteChildren,
)

interface routerProtectedRouteChildren {
  routerShellRoute: typeof routerShellRouteWithChildren
  featuresLegalAcceptDotrouteRoute: typeof featuresLegalAcceptDotrouteRoute
}

const routerProtectedRouteChildren: routerProtectedRouteChildren = {
  routerShellRoute: routerShellRouteWithChildren,
  featuresLegalAcceptDotrouteRoute: featuresLegalAcceptDotrouteRoute,
}

const routerProtectedRouteWithChildren = routerProtectedRoute._addFileChildren(
  routerProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  routerIndexDotrouteRoute: routerIndexDotrouteRoute,
  featuresAuthMagicLinkDotrouteRoute: featuresAuthMagicLinkDotrouteRoute,
  featuresBillingPricingDotrouteRoute: featuresBillingPricingDotrouteRoute,
  featuresAuthResetPasswordDotrouteRoute:
    featuresAuthResetPasswordDotrouteRoute,
  featuresAuthTwoFactorDotrouteRoute: featuresAuthTwoFactorDotrouteRoute,
  featuresAuthVerifyEmailDotrouteRoute: featuresAuthVerifyEmailDotrouteRoute,
  routerGuestRoute: routerGuestRouteWithChildren,
  routerProtectedRoute: routerProtectedRouteWithChildren,
  featuresInvitationsAcceptDotrouteRoute:
    featuresInvitationsAcceptDotrouteRoute,
  featuresDevelopersEventsDotrouteRoute: featuresDevelopersEventsDotrouteRoute,
  featuresLegalAccessibilityDotrouteRoute:
    featuresLegalAccessibilityDotrouteRoute,
  featuresLegalCookiesDotrouteRoute: featuresLegalCookiesDotrouteRoute,
  featuresLegalDataRightsDotrouteRoute: featuresLegalDataRightsDotrouteRoute,
  featuresLegalPrivacyPolicyDotrouteRoute:
    featuresLegalPrivacyPolicyDotrouteRoute,
  featuresLegalSubProcessorsDotrouteRoute:
    featuresLegalSubProcessorsDotrouteRoute,
  featuresLegalTermsDotrouteRoute: featuresLegalTermsDotrouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
