import type { EventType } from "./event-types";

export type Visibility = "public" | "internal";

export const VISIBILITY = {
  "user.created": "public",
  "user.signed_in": "public",
  "user.signed_out": "public",
  "user.email_verified": "public",
  "user.password_reset.requested": "internal",
  "user.password_changed": "internal",
  "user.magic_link.requested": "internal",
  "user.mfa.enabled": "internal",
  "user.mfa.disabled": "internal",
  "user.mfa.backup_codes_regenerated": "internal",
  "user.mfa.backup_code_used": "internal",
  "user.passkey.added": "internal",
  "user.passkey.removed": "internal",
  "user.account.linked": "internal",
  "user.account.unlinked": "internal",
  "user.deletion.requested": "public",
  "user.deletion.cancelled": "public",
  "user.deleted": "public",
  "user.profile.updated": "public",
  "user.email.change_requested": "internal",
  "user.export.requested": "internal",
  "user.export.completed": "internal",
  "org.created": "public",
  "org.updated": "public",
  "org.deleted": "public",
  "org.member.invited": "public",
  "org.member.joined": "public",
  "org.invitation.cancelled": "public",
  "org.member.removed": "public",
  "org.member.role_changed": "public",
  "upload.requested": "public",
  "upload.confirmed": "public",
  "upload.deleted": "public",
  "webhook.endpoint.created": "internal",
  "webhook.endpoint.updated": "internal",
  "webhook.endpoint.deleted": "internal",
  "webhook.test": "internal",
  "webhook.endpoint.secret_rotated": "internal",
  "webhook.endpoint.disabled": "internal",
  "webhook.delivery.exhausted": "internal",
  "api_token.created": "public",
  "api_token.revoked": "public",
  "api_token.used": "internal",
  "user.policy.accepted": "public",
  "user.cookie_consent.granted": "public",
  "user.cookie_consent.withdrawn": "public",
  "security.rate_limit.exceeded": "internal",
  "security.csp.violation": "internal",
  "security.csrf.rejected": "internal",
  "security.password.breached": "internal",
  "security.signup.rejected": "internal",
  "security.operator.audit_accessed": "internal",
  "billing.subscription.created": "public",
  "billing.subscription.updated": "public",
  "billing.subscription.cancelled": "public",
  "billing.payment.failed": "public",
  "billing.quota.exceeded": "internal",
  "admin.impersonation.started": "internal",
  "admin.impersonation.stopped": "internal",
  "admin.user.banned": "internal",
  "admin.user.unbanned": "internal",
  "admin.user.role_changed": "internal",
  "admin.user.password_reset": "internal",
  "admin.user.sessions_revoked": "internal",
  "email.delivery.exhausted": "internal",
  "notification.preference.updated": "internal",
  "notification.org_preference.updated": "internal",
  "sso.provider.registered": "internal",
  "sso.provider.updated": "internal",
  "sso.provider.deleted": "internal",
  "sso.domain.verified": "internal",
  "sso.enforcement.changed": "internal",
  "sso.login.success": "public",
  "sso.login.failure": "public",
  "scim.connection.created": "internal",
  "scim.connection.deleted": "internal",
  "scim.user.created": "public",
  "scim.user.updated": "public",
  "scim.user.deactivated": "public",
  "scim.user.deprovisioned": "public",
} satisfies Record<EventType, Visibility>;

export function isPublicEvent(eventType: EventType): boolean {
  return VISIBILITY[eventType] === "public";
}
